manage credit frontend
JeekStudio/StudentPlatform pull request #122
Opened 2019-02-24 09:25 UTC by alienmao

2019-03-03 15:42 UTC, nichujie commented on society_bureau/api/views.py
> +            return Response(status=status.HTTP_404_NOT_FOUND)
这里就不用检查year和semester了，如果不合法，filter之后自然就是空的，前端显示“本学期没有学分信息即可“

2019-03-03 15:56 UTC, nichujie commented on society_bureau/api/views.py
>          credit_distribution_sets = []
别用这个逻辑写，这样他没事做往前查一年就会多出一坨来。而且如果是在创建中，会很久之后才返回，显得很卡。

2019-03-03 15:57 UTC, nichujie commented on society_bureau/api/views.py
>          credit_distribution_sets = []
前端加个按钮可以开关所有credit的（就是model里那个closed属性），写在这个按钮的逻辑里：开启所有credit，如果当前学期还没有credit，则会创建。

2019-03-03 15:58 UTC, nichujie commented on society_bureau/api/views.py
>          credit_distribution_sets = []
查询就让他纯查询，和上面说的那样，反正空的queryset也能paginate

2019-03-03 16:09 UTC, nichujie commented on react/src/shared/YearSemesterSelect/YearSemesterSelect.js
>                  </Select>
![image](https://user-images.githubusercontent.com/17191827/53697944-6ae0e300-3e11-11e9-8f25-e9f694cdc66d.png)
页面刚加载的时候需要有个默认的值，不能是空的。像上图那样，每个select加个“全部”选项，value设为空字符串（不是null），key为0，上来<Select>的default-key为0。这样后端的query_params里面即使有这个key，它的值为空的时候也不会被处理。

2019-03-03 16:10 UTC, nichujie commented on react/src/shared/YearSemesterSelect/YearSemesterSelect.js
>                  </Select>
![image](https://user-images.githubusercontent.com/17191827/53697974-c9a65c80-3e11-11e9-9737-79b26fb8947f.png)
如上图，虽然query_params有semester，但值是空的，所以实际上返回所有2019年的credit（第1和2学期）

2019-03-03 16:10 UTC, nichujie requested changes
还是尽量一个按钮对应一个action吧

2019-03-03 23:31 UTC, alienmao commented on society_bureau/api/views.py
>          credit_distribution_sets = []
> 前端加个按钮可以开关所有credit的（就是model里那个closed属性），写在这个按钮的逻辑里：开启所有credit，如果当前学期还没有credit，则会创建。

那tmd这逻辑也很复杂了

2019-03-03 23:33 UTC, alienmao commented
还是list只返回list
create就是create
但这样也很傻逼， create一次只能create一个 ，又要自己写一个create

还不如如果有 就 返回 ，没有就批量创建 也就是listOrBulkCreate

2019-03-03 23:35 UTC, alienmao commented
```
if year and int(year) > SettingsService.get('year'):
            return Response(status=status.HTTP_404_NOT_FOUND)
        if year and int(year) == SettingsService.get('year') and (semester and int(semester) > SettingsService.get('semester')):
            return Response(status=status.HTTP_404_NOT_FOUND)
```
这一段是这样的:
比如现在是2019学年的第一学期，那么我查询2020学年的第一学期的话，因为queryset为空，所以按原来的代码 会自动生成2020学年第一学期的CD
但在前面先行进行了一次判断
如果现在是2019学年的第一学期，那么我查询2020学年的第一学期的话， 返回404
查询2019学年第二学期也返回404

2019-03-03 23:36 UTC, alienmao commented
这里的最烦的是，让社团部去创建CreditDistribution

2019-03-03 23:38 UTC, alienmao commented on society_bureau/api/views.py
>          credit_distribution_sets = []
> 别用这个逻辑写，这样他没事做往前查一年就会多出一坨来。而且如果是在创建中，会很久之后才返回，显得很卡。

因为按照计划这个系统在2019学年的第一学期才会开始使用
而且前端写了一个2019学年为第一年了

往前查到 比如 2018年 那只能是他们手动打url了

2019-03-04 00:56 UTC, nichujie commented
思考下有什么好一点的逻辑

2019-03-04 00:57 UTC, nichujie commented
或者我觉得放在一键设置里面创建也可以

2019-03-04 01:21 UTC, alienmao commented
不管怎么样
都需要实现 list bulkCreate create三个功能
所以不如把list和bulkCreate合在一起

2019-03-04 02:38 UTC, nichujie commented
我知道，我上面看懂了，那就前端加个提示，后端就这样吧。前端查询按钮上加个tooltip，然后loading的自定义文字提示一下，如果查询时间较长，就是正在创建

2019-03-04 02:41 UTC, nichujie commented
或者之前还有个想法，是改Settings的时候自动生成，好像也不是很好

2019-03-04 02:59 UTC, alienmao commented
> 我知道，我上面看懂了，那就前端加个提示，后端就这样吧。前端查询按钮上加个tooltip，然后loading的自定义文字提示一下，如果查询时间较长，就是正在创建

这样，那就List还是单纯的list
我写一个bulk_create

前端先查询 如果结果为空 则弹出一个是否要创建的Modal 如果选择 创建 就 创建并返回
不为空 直接展示

2019-03-04 11:12 UTC, nichujie commented on society_bureau/api/views.py
> +            for society in Society.objects.filter(status=SocietyStatus.WAITING):
应该是active吧

2019-03-04 11:16 UTC, nichujie commented on society_bureau/api/views.py
> +                )
还有就是，models里面cd是这样的：
![image](https://user-images.githubusercontent.com/17191827/53730000-a501c180-3eb1-11e9-98c0-4aa7d44868a0.png)
所以不清楚你这样创建会不会报错（比较神奇的情况是社团部先手抖创建了一个社团的cd，之后又想创建所有的，这样是有可能会报错的）
要么就：
1. 每个社团创建一个serializer，判断valid后create
2. create前直接if判断

2019-03-04 11:21 UTC, nichujie commented on society_bureau/api/views.py
> +                )
随之而来一个奇怪的问题就是如果这学期先新建了一个社团的cd，再查询就会有1个结果，批量创建的modal就不会弹出来，这个功能就消失了

2019-03-04 11:24 UTC, nichujie commented on society_bureau/api/views.py
> +                )
我的想法是，弹出modal可以保留，另外批量创建可以也放一个按钮在单独创建边上，这样平时也能找得到。

2019-03-04 11:36 UTC, alienmao commented on society_bureau/api/views.py
> +                )
serializer的validate好像不检查unique的吧

2019-03-04 11:42 UTC, alienmao commented
看来又要改测试了，md

2019-03-04 11:44 UTC, nichujie commented
好像是查的，无所谓，写下测试试试就知道了

2019-03-04 12:05 UTC, merged