Cn/activity request&credit models
JeekStudio/StudentPlatform pull request #40
Opened 2019-02-04 15:34 UTC by nichujie

* 增加ActivityRequest的model
* 社团model增加credit（学分上限）和tags
* 增加CreditReceivers的model
* 增加SiteSettings的model（数据库存json纯文本，方便前端增减设置，后端要用直接解析，不用再动models）

2019-02-04 16:05 UTC, harveyqiu requested changes

2019-02-04 16:05 UTC, alienmao commented on society/models.py
> +
created_at, updated_at

2019-02-04 16:06 UTC, harveyqiu requested changes

2019-02-04 16:06 UTC, alienmao commented on society/models.py
> +    tags = models.ManyToManyField(SocietyTag)
blank

2019-02-04 16:06 UTC, harveyqiu requested changes

2019-02-04 16:06 UTC, alienmao commented on society/models.py
> +    credit = models.PositiveSmallIntegerField(default=0)
float

2019-02-04 16:47 UTC, nichujie commented on society/models.py
> +    credit = models.PositiveSmallIntegerField(default=0)
按人头的，好算上限，float不好比较

2019-02-05 02:28 UTC, harveyqiu commented on society/models.py
> +    credit = models.PositiveSmallIntegerField(default=0)
加个comment
再加个help_text

2019-02-05 02:30 UTC, harveyqiu requested changes
加个comment
和help_text(django的

2019-02-05 11:03 UTC, harveyqiu approved these changes

2019-02-05 11:06 UTC, merged