Cn/activity views
JeekStudio/StudentPlatform pull request #51
Opened 2019-02-08 11:09 UTC by nichujie

对qsm好一点
sb的activity留到下一次写

2019-02-08 14:42 UTC, harveyqiu requested changes

2019-02-08 14:42 UTC, alienmao commented on society_manage/api/views.py
> +    serializer_class = ActivityRequestSerializer
这里可以去掉了
下面get_serializer_class了

2019-02-08 14:42 UTC, alienmao commented on society_manage/api/tests.py
> +        self.assertEqual(response.status_code, 403)
create和destroy测试了？

2019-02-08 14:42 UTC, alienmao commented on society_manage/api/tests.py
> +        self.assertEqual(response.data[1]['title'], 'make epic shit')
fields = '__all__' 了
content为什么没assert一下？

2019-02-08 14:42 UTC, alienmao commented on utils/permissions.py
> +    def has_permission(self, request, view):
不用写
继承的父类的这个方法本身就返回true了

2019-02-08 14:42 UTC, alienmao commented on society_manage/api/views.py
> +    def get_queryset(self):
这个移到 这个类的最前面

2019-02-08 14:44 UTC, alienmao commented on society_manage/api/views.py
> +            permission_classes = [IsSociety, SocietyActivityEditable]
还是用元组吧，drf自己用的就是tuple

2019-02-08 14:47 UTC, harveyqiu requested changes

2019-02-08 14:47 UTC, alienmao commented on society_manage/api/views.py
> +        elif self.action == 'list':
不是if判个是不是list就好了？
上面判retrieve不用

2019-02-09 06:24 UTC, harveyqiu requested changes

2019-02-09 06:24 UTC, alienmao commented on society_manage/api/tests.py
> +        self.assertEqual(self.ar1.content, 'pick hanzo or die')
content的测试是对api的测试 而不是对 模型的测试

2019-02-09 06:25 UTC, harveyqiu requested changes

2019-02-09 06:25 UTC, alienmao commented on society_manage/api/tests.py
> +        self.assertEqual(response.data[1]['title'], 'make epic shit')
content的assert应该写在这里
self.assertEqual(response.data[0]['content'], )

2019-02-09 06:34 UTC, nichujie commented on society_manage/api/tests.py
> +        self.assertEqual(self.ar1.content, 'pick hanzo or die')
我重写了个retrieve, list里面没有content

2019-02-09 06:36 UTC, harveyqiu approved these changes

2019-02-09 06:48 UTC, merged