CN/ sb manage society views
JeekStudio/StudentPlatform pull request #53
Opened 2019-02-09 15:43 UTC by nichujie

完成了管理社团的views和tests，关于credit的只写了serializer和部分views，先不要看。

models里面加了个related_name，两个migration还有一个是上次的help_text

2019-02-10 13:42 UTC, harveyqiu requested changes

2019-02-10 13:42 UTC, alienmao commented on society_manage/models.py
> +    receivers = models.ForeignKey(Student, on_delete=models.DO_NOTHING, blank=True, null=True)
receivers是复数吧，Student用了foreign key那么就是单数？
搞啥？

2019-02-10 14:08 UTC, alienmao commented on society_bureau/api/tests.py
> +            semester=2)
这括号放这好难受

2019-02-10 14:10 UTC, alienmao commented on society_bureau/api/tests.py
> +        self.assertEqual(response.data[0]['id'], 2)
不用测试retrieve的吗

2019-02-10 14:11 UTC, nichujie commented on society_bureau/api/tests.py
> +        self.assertEqual(response.data[0]['id'], 2)
还没写完，写完一起cue你

2019-02-10 14:11 UTC, alienmao commented
CreditReceiver部分没写完吧...

2019-02-10 14:29 UTC, alienmao commented on society_bureau/api/views.py
> +        if 'credit' in request.data.keys() and int(request.data['credit']) >= 0:
https://www.django-rest-framework.org/api-guide/serializers/#field-level-validation

2019-02-10 14:31 UTC, alienmao commented on society_bureau/api/views.py
> +        if 'credit' in request.data.keys() and int(request.data['credit']) >= 0:
用serializer

2019-02-10 14:51 UTC, alienmao commented on society_bureau/api/views.py
> +        return Society.objects.all()
只需要返回 建立的社团

2019-02-10 15:41 UTC, nichujie commented on society_bureau/api/views.py
> +        return Society.objects.all()
这个社团model还没改，所以还不能写。放在下次pr里面写吧，我在quip记下了。这个branch别删

2019-02-11 07:57 UTC, harveyqiu requested changes

2019-02-11 07:57 UTC, alienmao commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
这什么啊，引入不用什么鬼

2019-02-11 07:58 UTC, harveyqiu requested changes

2019-02-11 07:58 UTC, alienmao commented on society_bureau/api/tests.py
> +        self.assertEqual(response.data[0]['id'], 2)
为什么还是没有retrieve

2019-02-11 08:01 UTC, nichujie commented on society_bureau/api/tests.py
> +        self.assertEqual(response.data[0]['id'], 2)
不是说credit receivers放下一次，我就没写了

2019-02-11 08:02 UTC, nichujie commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
credit receiver用的，你说下次写，就先放着

2019-02-11 08:02 UTC, alienmao commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
移掉，要么注释掉

2019-02-11 08:05 UTC, nichujie commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
那credit receiver的测试就挂了，这个用了的，在下面

2019-02-11 08:06 UTC, nichujie commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
那我干脆底下的也commit了？

2019-02-11 08:06 UTC, nichujie commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
或者你干脆让我credit receiver也写完算了

2019-02-11 08:09 UTC, alienmao commented on society_bureau/api/serializers.py
> +from society.api.serializers import SocietyMiniField
credit receiver的部分都注释掉，包括test
有问题吗？

2019-02-11 09:33 UTC, merged